In [1]:
import pandas as pd
import sqlite3

In [2]:
df = pd.read_csv("Car_Data.csv")

In [3]:
df.head()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0

In [4]:
df.shape

(301, 9)

In [5]:
conn = sqlite3.connect("car_database.db")

In [6]:
df.to_sql("cars", conn, if_exists="replace", index=False)

301

In [7]:
query = "SELECT * FROM cars LIMIT 5;"
result = pd.read_sql(query, conn)
result

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0

In [8]:
pd.read_sql("SELECT COUNT(*) AS total_cars FROM cars;", conn)

   total_cars
0         301

In [9]:
query = """
SELECT *
FROM cars;
"""

result = pd.read_sql(query, conn)
result

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,brio,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0
300,brio,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [11]:
df.columns.tolist()

['Car_Name',
 'Year',
 'Selling_Price',
 'Present_Price',
 'Kms_Driven',
 'Fuel_Type',
 'Seller_Type',
 'Transmission',
 'Owner']

In [12]:
query = """
SELECT Car_Name, Year, Selling_Price, Fuel_Type, Transmission
FROM cars;
"""

result = pd.read_sql(query, conn)
result.head(10)

        Car_Name  Year  Selling_Price Fuel_Type Transmission
0           ritz  2014           3.35    Petrol       Manual
1            sx4  2013           4.75    Diesel       Manual
2           ciaz  2017           7.25    Petrol       Manual
3        wagon r  2011           2.85    Petrol       Manual
4          swift  2014           4.60    Diesel       Manual
5  vitara brezza  2018           9.25    Diesel       Manual
6           ciaz  2015           6.75    Petrol       Manual
7        s cross  2015           6.50    Diesel       Manual
8           ciaz  2016           8.75    Diesel       Manual
9           ciaz  2015           7.45    Diesel       Manual

In [15]:
query = """
SELECT Car_Name, Year, Selling_Price
FROM cars
WHERE year > 2018;
"""

result = pd.read_sql(query, conn)
result

Empty DataFrame
Columns: [Car_Name, Year, Selling_Price]
Index: []

In [16]:
query = """
SELECT Car_Name, Year, Selling_Price
FROM cars
ORDER BY Selling_Price DESC;
"""

result = pd.read_sql(query, conn)
result.head(10)

       Car_Name  Year  Selling_Price
0  land cruiser  2010          35.00
1      fortuner  2017          33.00
2      fortuner  2015          23.50
3      fortuner  2015          23.00
4        innova  2017          23.00
5      fortuner  2015          23.00
6        innova  2016          20.75
7      fortuner  2014          19.99
8        innova  2017          19.75
9      fortuner  2014          18.75

In [17]:
query = """
SELECT Car_Name, Year, Selling_Price
FROM cars
ORDER BY Selling_Price DESC
LIMIT 5;
"""

result = pd.read_sql(query, conn)
result

       Car_Name  Year  Selling_Price
0  land cruiser  2010           35.0
1      fortuner  2017           33.0
2      fortuner  2015           23.5
3      fortuner  2015           23.0
4        innova  2017           23.0

In [18]:
query = """
SELECT Fuel_Type, COUNT(*) AS Total_Cars
FROM cars
GROUP BY Fuel_Type;
"""

result = pd.read_sql(query, conn)
result

  Fuel_Type  Total_Cars
0       CNG           2
1    Diesel          60
2    Petrol         239

In [19]:
query = """
SELECT Fuel_Type,
       AVG(Selling_Price) AS Average_Selling_Price
FROM cars
GROUP BY Fuel_Type;
"""

result = pd.read_sql(query, conn)
result

  Fuel_Type  Average_Selling_Price
0       CNG               3.100000
1    Diesel              10.278500
2    Petrol               3.264184

In [20]:
query = """
SELECT
    MAX(Selling_Price) AS Highest_Price,
    MIN(Selling_Price) AS Lowest_Price
FROM cars;
"""

result = pd.read_sql(query, conn)
result

   Highest_Price  Lowest_Price
0           35.0           0.1

In [21]:
query = """
SELECT DISTINCT Fuel_Type
FROM cars;
"""

result = pd.read_sql(query, conn)
result

  Fuel_Type
0    Petrol
1    Diesel
2       CNG

In [22]:
query = """
SELECT Car_Name, Year, Selling_Price
FROM cars
WHERE Car_Name LIKE '%Honda%';
"""

result = pd.read_sql(query, conn)
result

                  Car_Name  Year  Selling_Price
0     Honda CB Hornet 160R  2017           0.80
1     Honda CB Hornet 160R  2017           0.75
2            Honda CBR 150  2014           0.65
3     Honda CB Hornet 160R  2016           0.60
4            Honda CBR 150  2013           0.60
5          Honda Activa 4G  2017           0.48
6        Honda Dream Yuga   2017           0.48
7          Honda Activa 4G  2017           0.45
8         Honda CB Trigger  2013           0.42
9         Honda CB Unicorn  2015           0.38
10  Hero Honda CBZ extreme  2011           0.38
11           Honda Karizma  2011           0.35
12        Honda Activa 125  2016           0.35
13           Honda Karizma  2010           0.31
14  Hero Honda Passion Pro  2012           0.30
15          Honda CB Shine  2013           0.30
16        Honda CB twister  2013           0.25
17        Honda CB twister  2010           0.16
18          Honda CB Shine  2007           0.12

In [23]:
query = """
SELECT Car_Name, Year, Selling_Price
FROM cars
WHERE Year BETWEEN 2017 AND 2019;
"""

result = pd.read_sql(query, conn)
result

                     Car_Name  Year  Selling_Price
0                        ciaz  2017           7.25
1               vitara brezza  2018           9.25
2                    alto 800  2017           2.85
3                       ignis  2017           4.90
4                       swift  2017           6.00
5                        ciaz  2017           7.75
6                      innova  2017          18.00
7                    fortuner  2017          33.00
8                      innova  2017          19.75
9                      innova  2017          23.00
10              corolla altis  2017          17.00
11         UM Renegade Mojave  2017           1.70
12                  KTM RC200  2017           1.65
13          Bajaj Dominar 400  2017           1.45
14  Royal Enfield Classic 350  2017           1.35
15  Royal Enfield Classic 350  2017           1.20
16          Bajaj Avenger 220  2017           0.90
17       Honda CB Hornet 160R  2017           0.80
18          Yamaha FZ S V 2.0  2017           0.78
19       Honda CB Hornet 160R  2017           0.75
20          Bajaj Avenger 220  2017           0.75
21         TVS Apache RTR 160  2017           0.65
22            Honda Activa 4G  2017           0.48
23                 TVS Sport   2017           0.48
24          Honda Dream Yuga   2017           0.48
25            Honda Activa 4G  2017           0.45
26                  Activa 4g  2017           0.40
27                      xcent  2017           5.75
28                        i20  2017           7.90
29                  grand i10  2017           5.25
30                        eon  2017           3.50
31                      verna  2017           9.25
32                      verna  2017           9.10
33                       jazz  2017           6.50
34                       brio  2017           4.80
35                       city  2017          11.50

In [24]:
query = """
SELECT Car_Name, Year, Selling_Price
FROM cars
WHERE Selling_Price > (
    SELECT AVG(Selling_Price)
    FROM cars
);
"""

result = pd.read_sql(query, conn)
result

          Car_Name  Year  Selling_Price
0              sx4  2013           4.75
1             ciaz  2017           7.25
2    vitara brezza  2018           9.25
3             ciaz  2015           6.75
4          s cross  2015           6.50
..             ...   ...            ...
116           jazz  2016           6.40
117           city  2015           8.55
118           city  2016           9.50
119           city  2017          11.50
120           brio  2016           5.30

[121 rows x 3 columns]

In [25]:
query = """
WITH AveragePrice AS (
    SELECT AVG(Selling_Price) AS Avg_Price
    FROM cars
)
SELECT Car_Name, Year, Selling_Price
FROM cars, AveragePrice
WHERE Selling_Price > Avg_Price;
"""

result = pd.read_sql(query, conn)
result

          Car_Name  Year  Selling_Price
0              sx4  2013           4.75
1             ciaz  2017           7.25
2    vitara brezza  2018           9.25
3             ciaz  2015           6.75
4          s cross  2015           6.50
..             ...   ...            ...
116           jazz  2016           6.40
117           city  2015           8.55
118           city  2016           9.50
119           city  2017          11.50
120           brio  2016           5.30

[121 rows x 3 columns]

In [26]:
query = """
SELECT
    Car_Name,
    Year,
    Selling_Price,
    ROW_NUMBER() OVER (
        ORDER BY Selling_Price DESC
    ) AS Price_Rank
FROM cars;
"""

result = pd.read_sql(query, conn)
result.head(10)

       Car_Name  Year  Selling_Price  Price_Rank
0  land cruiser  2010          35.00           1
1      fortuner  2017          33.00           2
2      fortuner  2015          23.50           3
3      fortuner  2015          23.00           4
4        innova  2017          23.00           5
5      fortuner  2015          23.00           6
6        innova  2016          20.75           7
7      fortuner  2014          19.99           8
8        innova  2017          19.75           9
9      fortuner  2014          18.75          10

In [27]:
query = """
SELECT
    Car_Name,
    Year,
    Selling_Price,
    RANK() OVER (
        ORDER BY Selling_Price DESC
    ) AS Price_Rank
FROM cars;
"""

result = pd.read_sql(query, conn)
result.head(10)

       Car_Name  Year  Selling_Price  Price_Rank
0  land cruiser  2010          35.00           1
1      fortuner  2017          33.00           2
2      fortuner  2015          23.50           3
3      fortuner  2015          23.00           4
4        innova  2017          23.00           4
5      fortuner  2015          23.00           4
6        innova  2016          20.75           7
7      fortuner  2014          19.99           8
8        innova  2017          19.75           9
9      fortuner  2014          18.75          10

In [28]:
query = """
WITH RankedCars AS (
    SELECT
        Car_Name,
        Year,
        Selling_Price,
        RANK() OVER (
            ORDER BY Selling_Price DESC
        ) AS Price_Rank
    FROM cars
)
SELECT *
FROM RankedCars
WHERE Price_Rank <= 10;
"""

result = pd.read_sql(query, conn)
result

       Car_Name  Year  Selling_Price  Price_Rank
0  land cruiser  2010          35.00           1
1      fortuner  2017          33.00           2
2      fortuner  2015          23.50           3
3      fortuner  2015          23.00           4
4        innova  2017          23.00           4
5      fortuner  2015          23.00           4
6        innova  2016          20.75           7
7      fortuner  2014          19.99           8
8        innova  2017          19.75           9
9      fortuner  2014          18.75          10

In [29]:
query = """
CREATE VIEW IF NOT EXISTS expensive_cars AS
SELECT
    Car_Name,
    Year,
    Selling_Price,
    Fuel_Type,
    Transmission
FROM cars
WHERE Selling_Price > 500000;
"""

conn.execute(query)
conn.commit()

In [30]:
query = """
SELECT *
FROM expensive_cars;
"""

result = pd.read_sql(query, conn)
result

Empty DataFrame
Columns: [Car_Name, Year, Selling_Price, Fuel_Type, Transmission]
Index: []

In [31]:
query = """
SELECT COUNT(*) AS Total_Expensive_Cars
FROM expensive_cars;
"""

result = pd.read_sql(query, conn)
result

   Total_Expensive_Cars
0                     0

In [32]:
from sqlalchemy import create_engine

In [33]:
engine = create_engine("sqlite:///car_database.db")

In [34]:
query = """
SELECT
    Fuel_Type,
    AVG(Selling_Price) AS Average_Selling_Price
FROM cars
GROUP BY Fuel_Type;
"""

result = pd.read_sql(query, engine)
result

  Fuel_Type  Average_Selling_Price
0       CNG               3.100000
1    Diesel              10.278500
2    Petrol               3.264184

In [35]:
query = """
SELECT
    Car_Name,
    Year,
    Selling_Price
FROM cars
ORDER BY Selling_Price DESC
LIMIT 5;
"""

result = pd.read_sql(query, engine)
result

       Car_Name  Year  Selling_Price
0  land cruiser  2010           35.0
1      fortuner  2017           33.0
2      fortuner  2015           23.5
3      fortuner  2015           23.0
4        innova  2017           23.0

In [36]:
conn.close()

In [37]:
from database_utils import run_query

In [38]:
query = """
SELECT Car_Name, Year, Selling_Price
FROM cars
ORDER BY Selling_Price DESC
LIMIT 5;
"""

result = run_query(query)
result

       Car_Name  Year  Selling_Price
0  land cruiser  2010           35.0
1      fortuner  2017           33.0
2      fortuner  2015           23.5
3      fortuner  2015           23.0
4        innova  2017           23.0

In [39]:
query = """
SELECT Car_Name, Year, Selling_Price
FROM cars
ORDER BY Selling_Price DESC
LIMIT 5;
"""

result = pd.read_sql(query, engine)
result

       Car_Name  Year  Selling_Price
0  land cruiser  2010           35.0
1      fortuner  2017           33.0
2      fortuner  2015           23.5
3      fortuner  2015           23.0
4        innova  2017           23.0

In [40]:
query = """
SELECT
    Year,
    COUNT(*) AS Total_Cars,
    AVG(Selling_Price) AS Average_Selling_Price
FROM cars
GROUP BY Year
ORDER BY Year;
"""

result = pd.read_sql(query, engine)
result

    Year  Total_Cars  Average_Selling_Price
0   2003           2               1.300000
1   2004           1               1.500000
2   2005           4               2.487500
3   2006           4               1.437500
4   2007           2               0.160000
5   2008           7               1.002857
6   2009           6               2.816667
7   2010          15               5.262667
8   2011          19               2.375263
9   2012          23               3.841304
10  2013          33               3.540909
11  2014          38               4.762105
12  2015          61               5.927049
13  2016          50               5.213200
14  2017          35               6.209143
15  2018           1               9.250000

In [41]:
query = """
SELECT
    Fuel_Type,
    AVG(Selling_Price) AS Average_Selling_Price
FROM cars
GROUP BY Fuel_Type
ORDER BY Average_Selling_Price DESC
LIMIT 1;
"""

result = pd.read_sql(query, engine)
result

  Fuel_Type  Average_Selling_Price
0    Diesel                10.2785

In [42]:
query = """
SELECT
    Transmission,
    AVG(Selling_Price) AS Average_Selling_Price
FROM cars
GROUP BY Transmission
ORDER BY Average_Selling_Price DESC
LIMIT 1;
"""

result = pd.read_sql(query, engine)
result

  Transmission  Average_Selling_Price
0    Automatic                   9.42

In [43]:
query = """
SELECT
    Seller_Type,
    AVG(Selling_Price) AS Average_Selling_Price
FROM cars
GROUP BY Seller_Type
ORDER BY Average_Selling_Price DESC
LIMIT 1;
"""

result = pd.read_sql(query, engine)
result

  Seller_Type  Average_Selling_Price
0      Dealer               6.721692

In [44]:
query = """
SELECT
    Owner,
    AVG(Selling_Price) AS Average_Selling_Price
FROM cars
GROUP BY Owner
ORDER BY Average_Selling_Price DESC
LIMIT 1;
"""

result = pd.read_sql(query, engine)
result

   Owner  Average_Selling_Price
0      0               4.761552

In [45]:
query = """
SELECT
    Car_Name,
    COUNT(*) AS Number_of_Cars
FROM cars
GROUP BY Car_Name
ORDER BY Number_of_Cars DESC
LIMIT 10;
"""

result = pd.read_sql(query, engine)
result

        Car_Name  Number_of_Cars
0           city              26
1  corolla altis              16
2          verna              14
3       fortuner              11
4           brio              10
5         innova               9
6            i20               9
7           ciaz               9
8      grand i10               8
9           jazz               7

In [46]:
query = """
SELECT
    Car_Name,
    Year,
    Selling_Price
FROM cars
WHERE Selling_Price > (
    SELECT AVG(Selling_Price)
    FROM cars
)
ORDER BY Selling_Price DESC;
"""

result = pd.read_sql(query, engine)
result

          Car_Name  Year  Selling_Price
0     land cruiser  2010          35.00
1         fortuner  2017          33.00
2         fortuner  2015          23.50
3         fortuner  2015          23.00
4           innova  2017          23.00
..             ...   ...            ...
116  corolla altis  2010           4.75
117     etios liva  2014           4.75
118       etios gd  2015           4.75
119        etios g  2014           4.75
120          xcent  2015           4.75

[121 rows x 3 columns]

In [47]:
query = """
SELECT
    Fuel_Type,
    COUNT(*) AS Total_Cars
FROM cars
GROUP BY Fuel_Type
HAVING COUNT(*) > 20
ORDER BY Total_Cars DESC;
"""

result = pd.read_sql(query, engine)
result

  Fuel_Type  Total_Cars
0    Petrol         239
1    Diesel          60

In [48]:
query = """
SELECT
    Owner,
    COUNT(*) AS Total_Cars,
    AVG(Selling_Price) AS Average_Selling_Price
FROM cars
GROUP BY Owner
ORDER BY Average_Selling_Price DESC;
"""

result = pd.read_sql(query, engine)
result

   Owner  Total_Cars  Average_Selling_Price
0      0         290               4.761552
1      3           1               2.500000
2      1          10               1.970000